### ISSUE TITLE
Log Improvements [meta issue]

### ISSUE THREAD

**Issue by adizere** [informalsystems/hermes#1538]
- [x] #1800 
- [x] Put more structured data in logs, instrument more functions
- [x] #2846
- [x] #2142
- [x] #1013
- [x] #1529 
- [x] #1488
- [x] #1537
    - [ ] Document the relayer pipeline model (e.g., in an ADR or in the Hermes guide) as captured in this issue; the goal is that the relayer operators can use this documentation as a reference for understanding the log

- [x] #2031  

- [x] Refactoring suggestion by @mzabaluev:
    - https://github.com/informalsystems/ibc-rs/pull/2089#discussion_r854062751

____

#### For Admin Use

- [X] Not duplicate issue
- [X] Appropriate labels applied
- [X] Appropriate milestone (priority) applied
- [X] Appropriate contributors tagged
- [X] Contributor assigned/self-assigned

**Comment by adizere** [comment]
All done, closing. Go team!
