### ISSUE TITLE
Add support for channel upgradability

### ISSUE THREAD

**Issue by adizere** [informalsystems/hermes#2547]
## Summary

Spec here:
https://github.com/cosmos/ibc/blob/main/spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md

I expect this to look very similarly with the relayer fees upgrade.

```[tasklist]
## Core implementation
- [ ] Adapt to spec refactoring: https://github.com/cosmos/ibc/pull/999/files
```

```[tasklist]
## CLI Tasks
- [ ] https://github.com/informalsystems/hermes/issues/3237
- [ ] https://github.com/informalsystems/hermes/issues/3238
- [ ] https://github.com/informalsystems/hermes/issues/3239
```
```[tasklist]
## Channel Worker Tasks
- [ ] https://github.com/informalsystems/hermes/issues/3243
```
```[tasklist]
## Testing Tasks
- [ ] https://github.com/informalsystems/hermes/issues/3256
- [ ] https://github.com/informalsystems/hermes/issues/3246
- [ ] https://github.com/informalsystems/hermes/issues/3254
- [ ] https://github.com/informalsystems/hermes/issues/3255
```
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate milestone (priority) applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned
