### ISSUE TITLE
Tracking Issue for Packet Worker re-design

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2593]
This issue keeps track of all the work that needs to be done as part of the relayer framework re-design:

Issue list: https://github.com/informalsystems/hermes/labels/relayer-next

- [ ] PR that tracks the code changes: #2478 
- [ ] https://github.com/informalsystems/hermes/issues/2731
- [ ] https://github.com/informalsystems/hermes/issues/2730
- [ ] https://github.com/informalsystems/hermes/issues/2733
- [ ] https://github.com/informalsystems/hermes/issues/2732
- [x] #2597
- [x] #2598
- [ ] Guide for context-generic programming: https://github.com/informalsystems/context-generic-programming
- [ ] PR that tracks code documentation 
- [ ] PR that tracks testing

**Comment by soareschen** [comment]
Closing this as we will track it through the [`relayer-next` label](https://github.com/informalsystems/hermes/labels/relayer-next)
