### ISSUE TITLE
Add preliminary docs for the integration test framework

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2737]
## Summary

Document the integration test framework's API in order to provide context and guidance on how to use it to write tests. 

## Acceptance Criteria

- [x] #2933 
- [x] #3003 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by adizere** [comment]
Will the integration test framework become superseded due to the new Hermes (context-generic-based) architecture? If so, not sure we should beef up the docs at this point.


Copying @soareschen and @ljoss17.

**Comment by soareschen** [comment]
We could write new tests for the new relayer with more abstract tests, and probably even do model checking using Kani. But the current priority is on the relayer implementation, so new testing infrastructure will likely take at least half year to complete, and existing code will still need to be tested with the current test framework. So it might still be worthwhile to add some documentation and have more dev sessions on it.

**Comment by adizere** [comment]
Let's kick off this? At least a first iteration.
