### ISSUE TITLE
Reach minimal feature parity between Hermes v1.5 and current relayer

### ISSUE THREAD

**Issue by soareschen** [informalsystems/hermes#2926]
## Summary

This issue tracks the minimal set of issues that need to be resolved before we can include an MVP release of the new relayer within the current Hermes release.

## Tasks
- [x] #2763 
- [x] #2840 
- [x] #2732
- [x] #2984
- [x] #3035 
- [x] #2929

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
🎉
