### ISSUE TITLE
Implement a CLI subcommand for the new packet relayer

### ISSUE THREAD

**Issue by soareschen** [informalsystems/hermes#2929]
## Summary

The new packet relayer is shown to be working in the integration tests. In this issue we will integrate the new relayer with the existing `hermes` CLI, so that users can use it as an experimental alternative to the current packet worker.

This is currently blocked by #2732, as the packet worker would require an event source to know what packets to relay.

The exact design of the CLI would be up to the assignee. At the broad level, here are some things to consider:

### Subcommand Interface

The subcommand can look something like `hermes new-relay packet [...]` for relaying packets. We can later add new sub-subcommands for new functionalities for the new relayer.

We also need to decide whether to have the new packet relayer relay everything from the config, or only relay a subset of the channels. Since the new packet relayer is experimental, we might want to first restrict it to only relay a single channel. If so, we might want the CLI to require the user to specify the exact chain and channel to relay.

It is fine to introduce breaking changes to the subcommand later on, as it is meant to be an experimental MVP release.

### Feature Flag

We need to decide whether to include a compile-time `experimental` feature flag for the new relayer sub-commands. If it is behind a feature flag, then the general users would not be accidentally use the new relayer by default.

### Configuration

The new relayer may require different forms of configuration. We may want to define a separate config file format or config subsection and keep it compatible with the current relayer.

### Tasks
- [x] #3077
- [x] #3078
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
