### ISSUE TITLE
Add more documentation and tutorials for Hermes v1.5

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2952]
## Background

This issue tracks the work going into documenting the Hermes v1.5 code base. This work is part of the effort to make the code base more easily understandable for future end users and more easily maintainable by relayer developers.

## Tasks

- [ ] https://github.com/informalsystems/hermes/issues/2908

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
