### ISSUE TITLE
Integrate Hermes v1.5 with the current relayer CLI

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2953]
## Background
This issue tracks the work going into integrating Hermes v1.5 features and functionality into the current relayer CLI interface.
This is part of the ongoing effort of bringing the `relayer-next` code base up to feature parity with the current relayer.

## Tasks
- [ ] 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
Closing this in favor of having #2929 serve as the tracking issue for this OKR.
