### ISSUE TITLE
Add support for Solomachine relaying

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2954]
## Background
This issue tracks the work of adding support for relaying between Solomachine clients in Hermes v1.5.
This is part of the ongoing effort of adding support for non-Cosmos chains in Hermes v1.5.

## Tasks
- [ ]

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by seanchen1991** [comment]
Closing this issue in favor of #2924 for tracking the work on Cosmos<>Solomachine relaying
