### ISSUE TITLE
Tracking issue for improving the testability and maintainability 

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2956]
## Background
This issue tracks the work going into making Hermes v1.5 more easily testable and maintainable. 

## Tasks
- [ ] #2785 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
