### ISSUE TITLE
`MockChainContext` improvements and fixes

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#2957]
## Summary

The first iteration of `MockChainContext` was implemented in #2785 as part of the effort to improve the testability of Hermes v1.5. There is some follow-up work to do done, which this issue tracks.

## Tasks
- [ ] The semantics of `process_messages` should be atomic: the messages need to be either all being processed successfully at the same height, or all failed. So this means that methods like `self.receive_packet` should not directly update the chain state. Instead they should take the current pending chain state, and return a new chain state to be committed. The next message handler would take the chain state returned from the previous message handler. And if any message handling failed, the whole pending chain state is discarded.
- [ ] The `query_write_ack_event` method introduced by #2907 is currently stubbed with `todo!()`, and needs to be implemented.
- [ ] The `Message::RecvPacket`, `Message::AckPacket`, and `Message::TimeoutPacket` should not contain the client ID. The client ID should be retrieved by having a mapping from channel ID to client ID in the local chain state.
- [ ] The `PacketKey` used in `Message` should contain the following fields: `source_channel_id`, `source_port_id`, `destination_channel_id`, `destination_port_id`, `sequence`, `timeout_height`, `timeout_timestamp`. Whether to read from the source or channel ID depends on the specific message. For example, processing of `RecvPacket` would use the destination channel ID as the local channel ID.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
