### ISSUE TITLE
Tracking issue for DevRel-related work

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3005]
## Background

This issue attempts to capture some of the Hermes team's work fielding questions / fulfilling requests from ecosystem users. While many such questions and requests do not lend themselves well to being captured by a GitHub issue, the ones that do are tracked retroactively by this issue.

## Tasks

- [ ] 

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
