### ISSUE TITLE
Investigate/discuss the usage of `expect` in the chain endpoint

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3082]
## Summary

From #3065, a number of `expect` calls were found in [crates/relayer/src/chain/endpoint.rs](https://github.com/informalsystems/hermes/blob/master/crates/relayer/src/chain/endpoint.rs). Was there a particular reason why it was done this way? Should we switch these call sites to use the more conventional error handling pattern?

## Tasks

- [x] Decide on whether the `expect` calls in `endpoint.rs` should be changed or not
    - [x] If it is decided they should be changed, change them to follow the more conventional error handling pattern

____

#### For Admin Use

- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
