### ISSUE TITLE
Ensure that docs build on API docs CI job 

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3100]
## Background

#3076 pinned the API docs CI job to the `nightly-2023-02-09` Rust toolchain in order to avoid an `Error: could not document 'clap'`. 

@romac's proposal is as follows:
> I think we should strive to use the same Rust version that docs.rs uses to ensure that we can always publish our crates and have their docs build successfully on docs.rs.
>
> In general, I would expect these kind of issues to be fixed promptly in the Rust nightlies, hence we can probably safely ignore those when the docs build breaks because of a dependency.
>
> Also, it looks like docs.rs builds the docs with `cargo doc --no-deps` so we should probably update the job to avoid building docs for dependencies, which would have also resolved the issue at hand here.
>
> Additionally, we could ensure we use the same version as docs.rs by scraping the nightly version used there from https://docs.rs/about/builds and use that in our CI job.

## Tasks

- [ ] Pin our API docs CI jobs to the same version that docs.rs uses 
- [ ] Build our docs with `cargo doc --no-deps`

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
