### ISSUE TITLE
Wrapping up fee support in Hermes (ICS29)

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3169]
## Background

Follow up to #2788, which tracked the work we did on adding fee support in Hermes in Q1 2023. 

There is some lingering work to bring ICS29 integration over the finish line. This work is blocked on channel upgradeability going live in the ecosystem (this is planned to occur in Q2). Once channel upgradeability has been enabled, wrapping up fee support will be the next priority. 

## Tasks

```[tasklist]
- [ ] #3091 
- [ ] #3039 
```
____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
