### ISSUE TITLE
Port channel upgradeability into relayer-next

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3170]
## Background

ibc-go is planning on releasing [channel upgradeability](https://github.com/cosmos/ibc/blob/main/spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md) in Q2. As such, the requisite components of this feature will need to be implemented in Hermes for it to go live in the ecosystem. 

This issue tracks the threads of work that feed into the completion of implementing channel upgradeability in Hermes.

```[tasklist]
## Tasks
- [ ] Implement abstract IBC handshake components in relayer framework
- [ ] Implement channel upgradeability such that it can be performed in a manual ad-hoc fashion
- [ ] Implement an `auto_handshake` function similar to the `auto_relay` function
```
____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by seanchen1991** [comment]
Closing this as out-of-scope: porting channel upgradability will be implemented in Hermes v1.
