### ISSUE TITLE
Tracking issue for Q2 2023 DevRel-related work

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3197]
## Background

This issue captures some of the Hermes team's work fielding questions / fulfilling requests from ecosystem users in Q2 of 2023. While many such questions and requests do not lend themselves well to being captured by a GitHub issue, the ones that do are tracked retroactively by this issue.

```[tasklist]
- [ ] #3139
- [ ] #1152
- [ ] https://github.com/informalsystems/hermes/issues/3263
- [ ] https://github.com/informalsystems/hermes/issues/3281
- [ ] https://github.com/informalsystems/hermes/issues/3297
```
____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
