### ISSUE TITLE
Provide support for CosmWasm

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3199]
## Background

This issue tracks the work performed by the Hermes team towards supporting CosmWasm relaying. 

Ideally, Hermes does not need to be aware of CosmWasm events; it should be agnostic with regards to the applications that the events it relays are servicing. At the moment, though, Hermes is currently reliant upon the datagrams that pass through its relaying pipeline containing some SDK-specific fields, so there is work that needs to be done in order to enable this level of datagram agnosticism.

```[tasklist]
## Tasks
- [ ] #2809 
- [ ] #3190 
```

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
