### ISSUE TITLE
Get the `max_expected_time_per_block` using the `/genesis` endpoint

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3211]
## Background

We should take care of this [TODO](https://github.com/informalsystems/hermes/blob/master/crates/relayer/src/link/relay_path.rs#L291-L292) to get the `max_expected_time_per_block` using the `/genesis` endpoint in the `src_max_block_time` and `dst_max_block_time` functions.

## Tasks

- [ ] Refactor `src_max_block_time` and `dst_max_block_time` to use the `max_expected_time_per_block` field fetched from the `/genesis` endpoint

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
