### ISSUE TITLE
When Relayer-next merge into main branch

### ISSUE THREAD

**Issue by DaviRain-Su** [informalsystems/hermes#3260]
## Background

I would like to know when the relayer-next branch will be fully merged into the main branch.

## Tasks

- [ ] 

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
