### ISSUE TITLE
Improve the user experience around configuring Hermes

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3281]
## Background

Relayer operators have provided feedback on ways in which the experience around configuring Hermes for different chains could be improved. This issue captures the work that will need to be done in order to address this feedback, which mainly includes work on improving the `hermes config auto` command, as well as Hermes documentation. 

```[tasklist]
## Tasks
- [ ] https://github.com/informalsystems/hermes/issues/3282
- [ ] https://github.com/informalsystems/hermes/issues/3283
- [ ] https://github.com/informalsystems/hermes/issues/3284
- [ ] https://github.com/informalsystems/hermes/issues/3285
```
____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
