### ISSUE TITLE
Tracking issue for 2023 DevRel work

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3437]
## Background

This issue captures the Hermes team's work fielding questions / fulfilling requests from ecosystem users in Q3 of 2023. While many such questions and requests do not lend themselves well to being captured by a GitHub issue, the ones that do are tracked retroactively by this issue.

## Tasks

```[tasklist]
- [ ] #3195
- [ ] #3299
- [ ] #3298
- [ ] #3324
- [ ] #3397
- [ ] #3398
- [ ] https://github.com/informalsystems/hermes/issues/3443
- [ ] https://github.com/informalsystems/hermes/issues/3503
- [ ] https://github.com/informalsystems/hermes/issues/3549
- [ ] https://github.com/informalsystems/hermes/issues/3465
- [ ] https://github.com/informalsystems/hermes/issues/3563
- [ ] https://github.com/informalsystems/hermes/issues/3570
- [ ] https://github.com/informalsystems/hermes/issues/3593
```
____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
