### ISSUE TITLE
Tracking issue for Q3 2023 testing work

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3452]
## Background

This issue tracks the Hermes team's work on improving Hermes' testing infrastructure.

Note that this issue does not track the testing work on channel upgradability. That work is being tracked in #2547.

## Tasks

```[tasklist]
- [ ] https://github.com/informalsystems/hermes/issues/3453
- [ ] https://github.com/informalsystems/hermes/issues/3454
- [ ] https://github.com/informalsystems/hermes/issues/3455
```

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
