### ISSUE TITLE
Support relaying for Sovereign SDK chains

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3506]
## Background

As part of Sovereign's efforts to integrate IBC into the Sovereign SDK, they will require an IBC relayer that is capable of signing and sending Sovereign transactions. 

Currently, the plan is to implement the necessary functionality in the relayer-next framework in order to support Sovereign relaying. As such, this work will serve as relayer-next's first concrete use-case. 

## Tasks

- [ ] TODO

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
