### ISSUE TITLE
Collaborate with ibc-rs team on building a cohesive documentation portal for how to integrate with Hermes

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3507]
## Background

As part of the larger effort to build a one-stop shop for chain developers looking to integrate IBC, we'll be building out a comprehensive documentation portal that will serve as the landing page for devs looking to learn more about IBC and how to integrate it into their chains. 

This work is a collaboration with the ibc-rs team, who will be documenting how developers integrate ibc-rs's modules. We will be documenting how to integrate with Hermes. 

```[tasklist]
## Tasks
- [ ] https://github.com/informalsystems/hermes/issues/3571
```

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by adizere** [comment]
no longer relevant right now

will reopen later if becomes a priority
