### ISSUE TITLE
Reduce the surface area between ibc-rs and Hermes interfaces

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3508]
## Background

As part of our larger effort to build a one-stop shop for chain developers to looking to integrate IBC, it would desirable if we're able to offer a single cohesive interface for chain developers to conform against. 

The idea is that conforming to this one single interface will give chains access to IBC modules, relaying, misbehaviour detection, etc. This is as opposed to the current status quo when it comes to integrating IBC, where chain developers need to integrate on-chain modules and off-chain relayers separately.

The goal is to design a minimal interface that unlocks both on-chain and off-chain IBC components. 

## Problem Statement

The first step will involve consolidating the various `ibc-types` crates that are currently scattered around various repositories. These include:
- Hermes' [relayer-types](https://github.com/informalsystems/hermes/tree/master/crates/relayer-types) crate
- ibc-rs's [implementation](https://github.com/cosmos/ibc-rs/tree/main/crates/ibc)
- Penumbra's [ibc-types](https://github.com/penumbra-zone/ibc-types) crate

There are few different approaches that can be taken, listed in order from least desirable to most desirable:
- ~~Have Hermes depend on Penumbra's `ibc-types` crate~~
- Extract out the minimal types of types that are shared between ibc-rs and Hermes. Hermes would then depend on this set, as well as a separate crate containing the types that only Hermes depends on. 
- Move Penumbra's `ibc-types` fork back to the Cosmos org such that all three projects would depend on a single unified `ibc-types` crate. 

## Tasks
- [ ] Decide on which of the above listed approaches to take

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by adizere** [comment]
no longer a priority

will reopen if becomes a priority
