### ISSUE TITLE
Expose client expiration metrics

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3541]
## Background

A user on Discord had a gRPC problem which caused a worker to fail when performing a client update. If the user had an idea of how much time was left before the client expired, this issue could have been mitigated. So we should expose these metrics from Hermes, similar to how the Go relayer exposes them in this [PR](https://github.com/cosmos/relayer/pull/1235). 

## Tasks

- [ ] Export client expiration metrics to Prometheus

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
