### ISSUE TITLE
Transactions not getting relayed between localChain and BandChain testnet

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3570]
## Background

This question was originally raised in a [discussion thread](https://github.com/orgs/cosmos/discussions/42) in the Cosmos org:

> I've successfully set up a chain and an IBC enabled module using the Ignite CLI. My objective is to initiate Oracle requests from my module to the BandChain testnet (band-laozi-testnet6). To facilitate communication between the two chains, I've established a configuration involving a Hermes Relayer. I followed the steps outlined in this guide: Hermes Relayer Setup.
> 
> Upon completing this configuration process, I verified the establishment of a channel between the chains through two methods. Firstly, by executing the command:
> 
> `hermes query channels --show-counterparty --chain myChain`
>
> Alternatively, I observed the channel's presence by visiting the BandChain testnet explorer at: BandChain Testnet Explorer.
>
> However, I've encountered an issue when attempting to observe the packets I'm sending from my module to the BandChain. Specifically, I'm working on transmitting data from my module using the igniteCLI tool. I've implemented a `msg_server_oracle_request_packet_data.go` file that should be responsible for sending the required packet to the BandChain. Upon executing the CLI command, I receive a transaction hash. Although inspecting the transaction details reveals no errors, I've noticed that I'm not receiving any response from the BandChain. Furthermore, this transaction isn't visible on the BandChain testnet explorer.
>
> I'm open to suggestions or insights regarding why this setup might not be functioning as expected.
>
> Happy to share more information about my configuration if needed!

## Tasks

- [ ] Diagnose the problem causing this issue
    - [ ] Resolve the problem causing the issue

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by seanchen1991** [comment]
@AntoninPS Would you be able to provide your `config.toml`, as well as which version of Hermes you're running?

**Comment by AntoninPS** [comment]
Hello @seanchen1991, 

Thank you for creating the issue. 

I'm running Hermes version 1.6.0

Here is my config.toml:

```
# The global section has parameters that apply globally to the relayer operation.
[global]

# Specify the verbosity for the relayer logging output. Default: 'info'
# Valid options are 'error', 'warn', 'info', 'debug', 'trace'.
log_level = 'trace'


# Specify the mode to be used by the relayer. [Required]
[mode]

# Specify the client mode.
[mode.clients]

# Whether or not to enable the client workers. [Required]
enabled = true

# Whether or not to enable periodic refresh of clients. [Default: true]
# Note: Even if this is disabled, clients will be refreshed automatically if
#      there is activity on a connection or channel they are involved with.
refresh = true

# Whether or not to enable misbehaviour detection for clients. [Default: false]
misbehaviour = true

# Specify the connections mode.
[mode.connections]

# Whether or not to enable the connection workers for handshake completion. [Required]
enabled = true

# Specify the channels mode.
[mode.channels]

# Whether or not to enable the channel workers for handshake completion. [Required]
enabled = true

# Specify the packets mode.
[mode.packets]

# Whether or not to enable the packet workers. [Required]
enabled = true

# Parametrize the periodic packet clearing feature.
# Interval (in number of blocks) at which pending packets
# should be eagerly cleared. A value of '0' will disable
# periodic packet clearing. [Default: 100]
clear_interval = 100

# Whether or not to clear packets on start. [Default: false]
clear_on_start = true

# Toggle the transaction confirmation mechanism.
# The tx confirmation mechanism periodically queries the `/tx_search` RPC
# endpoint to check that previously-submitted transactions
# (to any chain in this config file) have delivered successfully.
# Experimental feature. Affects telemetry if set to false.
# [Default: true]
tx_confirmation = true

# The REST section defines parameters for Hermes' built-in RESTful API.
# https://hermes.informal.systems/rest.html
[rest]

# Whether or not to enable the REST service. Default: false
enabled = true

# Specify the IPv4/6 host over which the built-in HTTP server will serve the RESTful
# API requests. Default: 127.0.0.1
host = '127.0.0.1'

# Specify the port over which the built-in HTTP server will serve the restful API
# requests. Default: 3000
port = 3000


# The telemetry section defines parameters for Hermes' built-in telemetry capabilities.
# https://hermes.informal.systems/telemetry.html
[telemetry]

# Whether or not to enable the telemetry service. Default: false
enabled = true

# Specify the IPv4/6 host over which the built-in HTTP server will serve the metrics
# gathered by the telemetry service. Default: 127.0.0.1
host = '127.0.0.1'

# Specify the port over which the built-in HTTP server will serve the metrics gathered
# by the telemetry service. Default: 3001
port = 3001

[[chains]]
id = 'dreddsecure'
rpc_addr = 'http://localhost:26657'
grpc_addr = 'http://localhost:9090'
event_source = { mode = 'push', url = 'ws://localhost:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '100s'
account_prefix = 'cosmos'
key_name = 'requester'
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 15000000
gas_price = { price = 0, denom = 'ustake' }
gas_multiplier = 1.1
max_msg_num = 20
max_tx_size = 209715
clock_drift = '20s'
max_block_time = '100s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = 'allow'
list = [
   ['escrow', 'channel-0'],
]
# [chains.packet_filter]
# policy = 'allow'
# list = [
#    ['wasm.*', '*'],
# ]

[[chains]]
id = 'band-laozi-testnet6'
rpc_addr = 'https://rpc.laozi-testnet6.bandchain.org:443'
grpc_addr = 'https://laozi-testnet6.bandchain.org:443'
event_source = { mode = 'push', url = 'wss://rpc.laozi-testnet6.bandchain.org:443/websocket', batch_delay = '500ms' }
rpc_timeout = '100s'
account_prefix = 'band'
key_name = 'testkey'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 10000000
gas_price = { price = 0.0025, denom = 'uband' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '100s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = 'allow'
list = [
   ['oracle', 'channel-450'],
]
# [chains.packet_filter]
# policy = 'allow'
# list = [
#    ['oracle', '*'],
# ]
```

Happy to provide more information if needed !

Thanks

**Comment by ljoss17** [comment]
Hi @AntoninPS could you specify which Hermes version you are using?
I see that you have a specific filter for the `dreddsecure`:

```
list = [
   ['escrow', 'channel-0'],
]
```

But the error happens for `channel-4`, could you give us the full logs?

**Comment by AntoninPS** [comment]
@ljoss17 Im sorry for the confusion, I sent the error message of another configuration (I created a new config.toml because I did reset my chain). 

Yes, there is a specific filter for dreddsecure, as I did configure multiple channels for testing. The updated config.toml has this filter:
```
list = [
   ['escrow', 'channel-4'],
]
```

The Hermes version used is 1.6.0+1c1cf02

Thank for your feedback, let me know if you need any other information !

**Comment by seanchen1991** [comment]
> I sent the error message of another configuration (I created a new config.toml because I did reset my chain).

@AntoninPS Could you send us the most up-to-date error logs that you get with the correct configuration?

**Comment by AntoninPS** [comment]
@seanchen1991 Sure !

Hermes Version: 1.6.0+1c1cf02
ibc-go version: v7.1.0

most up-to-date error logs receive when running "hermes start": 
```
2023-08-25T17:32:50.533928Z ERROR ThreadId(24) spawn:chain{chain=dreddsecure}:client{client=07-tendermint-8}:connection{connection=connection-8}:channel{channel=channel-4}:worker.packet.cmd{src_chain=dreddsecure src_port=escrow src_channel=channel-4 dst_chain=band-laozi-testnet6}:relay{odata=cleared/debd5669 ->Source @0-10331197; len=4}:send_messages_and_wait_check_tx{chain=dreddsecure tracking_id=cleared/debd5669}:send_tx_with_account_sequence_retry{chain=dreddsecure account.sequence=44}:estimate_gas: failed to simulate tx. propagating error to caller: gRPC call `send_tx_simulate` failed with status: status: Unknown, message: "failed to execute message; message index: 1: timeout packet verification failed: packet commitment bytes are not equal: got ([165 221 232 78 48 132 242 235 95 143 232 159 123 175 19 55 238 228 190 30 30 123 190 108 161 140 180 112 32 210 93 209]), expected ([54 184 111 127 137 189 179 206 18 69 74 46 203 197 63 173 64 139 134 151 148 200 242 182 186 124 38 6 235 186 212 131]): invalid packet [cosmos/ibc-go/v7@v7.1.0/modules/core/04-channel/keeper/timeout.go:97] With gas wanted: '18446744073709551615' and gas used: '253130' ", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "17830"} }
2023-08-25T17:32:50.534088Z ERROR ThreadId(24) spawn:chain{chain=dreddsecure}:client{client=07-tendermint-8}:connection{connection=connection-8}:channel{channel=channel-4}:worker.packet.cmd{src_chain=dreddsecure src_port=escrow src_channel=channel-4 dst_chain=band-laozi-testnet6}:relay{odata=cleared/debd5669 ->Source @0-10331197; len=4}:send_messages_and_wait_check_tx{chain=dreddsecure tracking_id=cleared/debd5669}:send_tx_with_account_sequence_retry{chain=dreddsecure account.sequence=44}: gas estimation failed or encountered another unrecoverable error error=gRPC call `send_tx_simulate` failed with status: status: Unknown, message: "failed to execute message; message index: 1: timeout packet verification failed: packet commitment bytes are not equal: got ([165 221 232 78 48 132 242 235 95 143 232 159 123 175 19 55 238 228 190 30 30 123 190 108 161 140 180 112 32 210 93 209]), expected ([54 184 111 127 137 189 179 206 18 69 74 46 203 197 63 173 64 139 134 151 148 200 242 182 186 124 38 6 235 186 212 131]): invalid packet [cosmos/ibc-go/v7@v7.1.0/modules/core/04-channel/keeper/timeout.go:97] With gas wanted: '18446744073709551615' and gas used: '253130' ", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "17830"} }
2023-08-25T17:32:50.534216Z ERROR ThreadId(29) spawn:chain{chain=dreddsecure}:client{client=07-tendermint-8}:connection{connection=connection-8}:channel{channel=channel-4}:worker.packet.cmd{src_chain=dreddsecure src_port=escrow src_channel=channel-4 dst_chain=band-laozi-testnet6}: will retry: schedule execution encountered error: link failed with underlying error: gRPC call `send_tx_simulate` failed with status: status: Unknown, message: "failed to execute message; message index: 1: timeout packet verification failed: packet commitment bytes are not equal: got ([165 221 232 78 48 132 242 235 95 143 232 159 123 175 19 55 238 228 190 30 30 123 190 108 161 140 180 112 32 210 93 209]), expected ([54 184 111 127 137 189 179 206 18 69 74 46 203 197 63 173 64 139 134 151 148 200 242 182 186 124 38 6 235 186 212 131]): invalid packet [cosmos/ibc-go/v7@v7.1.0/modules/core/04-channel/keeper/timeout.go:97] With gas wanted: '18446744073709551615' and gas used: '253130' ", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "17830"} }
2023-08-25T17:32:50.534642Z  WARN ThreadId(29) spawn:chain{chain=dreddsecure}:client{client=07-tendermint-8}:connection{connection=connection-8}:channel{channel=channel-4}:worker.packet.cmd{src_chain=dreddsecure src_port=escrow src_channel=channel-4 dst_chain=band-laozi-testnet6}: task encountered ignorable error: link error: link failed with underlying error: gRPC call `send_tx_simulate` failed with status: status: Unknown, message: "failed to execute message; message index: 1: timeout packet verification failed: packet commitment bytes are not equal: got ([165 221 232 78 48 132 242 235 95 143 232 159 123 175 19 55 238 228 190 30 30 123 190 108 161 140 180 112 32 210 93 209]), expected ([54 184 111 127 137 189 179 206 18 69 74 46 203 197 63 173 64 139 134 151 148 200 242 182 186 124 38 6 235 186 212 131]): invalid packet [cosmos/ibc-go/v7@v7.1.0/modules/core/04-channel/keeper/timeout.go:97] With gas wanted: '18446744073709551615' and gas used: '253130' ", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "17830"} }
```

latest config.toml:
```
# The global section has parameters that apply globally to the relayer operation.
[global]

# Specify the verbosity for the relayer logging output. Default: 'info'
# Valid options are 'error', 'warn', 'info', 'debug', 'trace'.
log_level = 'trace'


# Specify the mode to be used by the relayer. [Required]
[mode]

# Specify the client mode.
[mode.clients]

# Whether or not to enable the client workers. [Required]
enabled = true

# Whether or not to enable periodic refresh of clients. [Default: true]
# Note: Even if this is disabled, clients will be refreshed automatically if
#      there is activity on a connection or channel they are involved with.
refresh = true

# Whether or not to enable misbehaviour detection for clients. [Default: false]
misbehaviour = true

# Specify the connections mode.
[mode.connections]

# Whether or not to enable the connection workers for handshake completion. [Required]
enabled = true

# Specify the channels mode.
[mode.channels]

# Whether or not to enable the channel workers for handshake completion. [Required]
enabled = true

# Specify the packets mode.
[mode.packets]

# Whether or not to enable the packet workers. [Required]
enabled = true

# Parametrize the periodic packet clearing feature.
# Interval (in number of blocks) at which pending packets
# should be eagerly cleared. A value of '0' will disable
# periodic packet clearing. [Default: 100]
clear_interval = 100

# Whether or not to clear packets on start. [Default: false]
clear_on_start = true

# Toggle the transaction confirmation mechanism.
# The tx confirmation mechanism periodically queries the `/tx_search` RPC
# endpoint to check that previously-submitted transactions
# (to any chain in this config file) have delivered successfully.
# Experimental feature. Affects telemetry if set to false.
# [Default: true]
tx_confirmation = true

# The REST section defines parameters for Hermes' built-in RESTful API.
# https://hermes.informal.systems/rest.html
[rest]

# Whether or not to enable the REST service. Default: false
enabled = true

# Specify the IPv4/6 host over which the built-in HTTP server will serve the RESTful
# API requests. Default: 127.0.0.1
host = '127.0.0.1'

# Specify the port over which the built-in HTTP server will serve the restful API
# requests. Default: 3000
port = 3000


# The telemetry section defines parameters for Hermes' built-in telemetry capabilities.
# https://hermes.informal.systems/telemetry.html
[telemetry]

# Whether or not to enable the telemetry service. Default: false
enabled = true

# Specify the IPv4/6 host over which the built-in HTTP server will serve the metrics
# gathered by the telemetry service. Default: 127.0.0.1
host = '127.0.0.1'

# Specify the port over which the built-in HTTP server will serve the metrics gathered
# by the telemetry service. Default: 3001
port = 3001

[[chains]]
id = 'dreddsecure'
rpc_addr = 'http://localhost:26657'
grpc_addr = 'http://localhost:9090'
event_source = { mode = 'push', url = 'ws://localhost:26657/websocket', batch_delay = '500ms' }
rpc_timeout = '100s'
account_prefix = 'cosmos'
key_name = 'requester'
store_prefix = 'ibc'
default_gas = 5000000
max_gas = 15000000
gas_price = { price = 0, denom = 'ustake' }
gas_multiplier = 1.1
max_msg_num = 20
max_tx_size = 209715
clock_drift = '20s'
max_block_time = '100s'
trusting_period = '10days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = 'allow'
list = [
   ['escrow', 'channel-4'],
]

[[chains]]
id = 'band-laozi-testnet6'
rpc_addr = 'https://rpc.laozi-testnet6.bandchain.org:443'
grpc_addr = 'https://laozi-testnet6.bandchain.org:443'
event_source = { mode = 'push', url = 'wss://rpc.laozi-testnet6.bandchain.org:443/websocket', batch_delay = '500ms' }
rpc_timeout = '100s'
account_prefix = 'band'
key_name = 'testkey'
store_prefix = 'ibc'
default_gas = 100000
max_gas = 10000000
gas_price = { price = 0.0025, denom = 'uband' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
max_block_time = '100s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
[chains.packet_filter]
policy = 'allow'
list = [
   ['oracle', 'channel-449'],
]
```

Thanks, let me know if you need more info :)

**Comment by ljoss17** [comment]
Could you share the logs with a few minutes before the error happening? Or if it takes less time to trigger, the full logs since you start the Hermes instance?

**Comment by romac** [comment]
FYI here is where the error above is thrown: https://github.com/cosmos/ibc-go/blob/e667ddab1f16955604bd43dd9fc227717877b285/modules/core/04-channel/keeper/timeout.go#L96-L99

**Comment by romac** [comment]
It could also be the `store_prefix` that's wrong, but I wouldn't know what to set it to.

**Comment by AntoninPS** [comment]
Hey, we managed to fix our issue. 

The issue was not with the relayer configuration itself, but how we encoded our ibcPacket, which was incompatible with the expected packets on the receiving chain (bandchain).

Thanks for your help
