### ISSUE TITLE
Add a metric that captures average tx message size

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3626]
## Background

It would be nice for Hermes to expose a metric that captures average tx message size within some time frame.

## Tasks

- [ ] Expose a `tx_avg_message_size` metric

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by romac** [comment]
We probably want a histogram rather than the plain average/median, which would let us derive the latter two.
