### ISSUE TITLE
Document `node is not persisting abci responses` error

### ISSUE THREAD

**Issue by seanchen1991** [informalsystems/hermes#3634]
## Background

An operator ran received an error `node is not persisting abci responses`. This error doesn't show up in the Hermes codebase, so it's likely coming from the underlying Comet node. 

It turns out this is probably caused by the underlying node being configured to `discard_abci_responses = true` when Hermes to set to use the pull-mode event source. We should document this interaction in the cross-comp-config section of the Hermes guide. 

## Tasks

- [ ] Document the above interaction in the Hermes guide

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
