### ISSUE TITLE
Support ICS 08 WASM clients wrapping an ICS 07 Tendermint client

### ISSUE THREAD

**Issue by romac** [informalsystems/hermes#3951]
WIP: https://github.com/informalsystems/hermes/pull/3943

## Acceptance Criteria

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
