### ISSUE TITLE
Tracking channel upgrade follow-up

### ISSUE THREAD

**Issue by ljoss17** [informalsystems/hermes#4013]
## Background

This issue tracks follow-up work from channel upgrade.

## Tasks

- [ ] https://github.com/informalsystems/hermes/issues/4011
- [ ] https://github.com/informalsystems/hermes/issues/4012

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
