### ISSUE TITLE
June 2024 CI Chain Versions Update

### ISSUE THREAD

**Issue by ljoss17** [informalsystems/hermes#4028]
## Background

Track the update of chain versions used in our CI system for June.

## Tasks

- [x] https://github.com/informalsystems/hermes/issues/4023
- [x] https://github.com/informalsystems/hermes/issues/4024
- [x] https://github.com/informalsystems/hermes/issues/4025
- [x] https://github.com/informalsystems/hermes/issues/4026
- [x] https://github.com/informalsystems/hermes/issues/4027
- [x] https://github.com/informalsystems/hermes/issues/4029

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
