### ISSUE TITLE
ICS20 v2 compatibility tracking

### ISSUE THREAD

**Issue by ljoss17** [informalsystems/hermes#4077]
## Background

ICS20 v2 will introduces multiples features which require changes on Hermes.
This issue will track all the changes needed in Hermes.

## Tasks

- [ ] ICS20 Multidenom transfer: https://github.com/informalsystems/hermes/issues/4006
- [ ] Packet data Protobuf encoding https://github.com/informalsystems/hermes/issues/4098

## Futur tasks

- [ ] https://github.com/informalsystems/hermes/issues/4078
   - This has been postponed and will not be released in the initial version of ICS20 v2

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by gjermundgaraba** [comment]
Given that ICS20 v2 was retracted and will not be released either, I will close this issue.
