### ISSUE TITLE
August 2024 CI Chain Versions Update 

### ISSUE THREAD

**Issue by ljoss17** [informalsystems/hermes#4112]
## Background

Track the update of chain versions used in our CI system for August.

## Tasks

- [ ] 

____

#### For Admin Use

- [ ] https://github.com/informalsystems/hermes/labels/tracking or https://github.com/informalsystems/hermes/labels/okr label (as well as any other appropriate labels) applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged

**Comment by ljoss17** [comment]
Completed
