### ISSUE TITLE
September 2024 CI Chain Versions Update

### ISSUE THREAD

**Issue by ljoss17** [informalsystems/hermes#4166]
## Background

Track the update of chain versions used in our CI system for September.

## Tasks

- [x] 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
